/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.team.user_management;

import deu.cse.team.mainmenu.AdminMenu;
import deu.cse.team.source.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 구본영
 */
public class User_Management extends javax.swing.JFrame {

    ArrayList<UserInfo> userinfo = new ArrayList<>();
    ArrayList<UserInfo> blackinfo = new ArrayList<>();
    /**
     * Creates new form User_Management
     */
    public User_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        User_Table = new javax.swing.JTable();
        Load_UserList_Button = new javax.swing.JButton();
        BlackList_Add_Button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Black_Table = new javax.swing.JTable();
        Load_BlackKList_Button = new javax.swing.JButton();
        BlackList_Del_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        User_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PW", "NAME", "EMAIL", "PHONE", "BRITH", "RESIDENCE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(User_Table);

        Load_UserList_Button.setText("불러오기");
        Load_UserList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_UserList_ButtonActionPerformed(evt);
            }
        });

        BlackList_Add_Button.setText("추가");
        BlackList_Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackList_Add_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Load_UserList_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlackList_Add_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Load_UserList_Button)
                        .addGap(18, 18, 18)
                        .addComponent(BlackList_Add_Button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("블랙리스트 추가", jPanel3);

        Black_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PW", "NAME", "EMAIL", "PHONE", "BRITH", "RESIDENCE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Black_Table);

        Load_BlackKList_Button.setText("불러오기");
        Load_BlackKList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_BlackKList_ButtonActionPerformed(evt);
            }
        });

        BlackList_Del_Button.setText("삭제");
        BlackList_Del_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackList_Del_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Load_BlackKList_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlackList_Del_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Load_BlackKList_Button)
                        .addGap(18, 18, 18)
                        .addComponent(BlackList_Del_Button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("블랙리스트 삭제", jPanel4);

        Back_Button.setText("이전");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back_Button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Load_UserList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_UserList_ButtonActionPerformed
        UserList Userdata = new UserList();
        
        
        DefaultTableModel usermodel = (DefaultTableModel) User_Table.getModel();
        usermodel.setNumRows(0);
        
        Userdata.FRead();
        Userdata.Split();
        
        try {
            userinfo = Userdata.returUserinfo();
        } catch (IOException ex) {
            Logger.getLogger(User_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0 ; i < userinfo.size() ; i++){
            usermodel.insertRow(usermodel.getRowCount(), new Object[]{
                userinfo.get(i).getId(),
                userinfo.get(i).getPw(),
                userinfo.get(i).getName(),
                userinfo.get(i).getEmail(),
                userinfo.get(i).getPhone(),
                userinfo.get(i).getBirth(),
                userinfo.get(i).getResidence()
            });
        }
    }//GEN-LAST:event_Load_UserList_ButtonActionPerformed

    private void Load_BlackKList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_BlackKList_ButtonActionPerformed
        UserList Blackdata = new UserList();
        
        DefaultTableModel blackmodel = (DefaultTableModel) Black_Table.getModel();
        blackmodel.setNumRows(0);
        
        Blackdata.BRead();
        Blackdata.BSplit();
        
        try {
            blackinfo = Blackdata.returnBlackinfo();
        } catch (IOException ex) {
            Logger.getLogger(User_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0 ; i < blackinfo.size() ; i++){
            blackmodel.insertRow(blackmodel.getRowCount(), new Object[]{
                blackinfo.get(i).getId(),
                blackinfo.get(i).getPw(),
                blackinfo.get(i).getName(),
                blackinfo.get(i).getEmail(),
                blackinfo.get(i).getPhone(),
                blackinfo.get(i).getBirth(),
                blackinfo.get(i).getResidence()
            });
        }
    }//GEN-LAST:event_Load_BlackKList_ButtonActionPerformed

    private void BlackList_Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackList_Add_ButtonActionPerformed
        try {
            DefaultTableModel usermodel = (DefaultTableModel) User_Table.getModel();
            int nRow = -1;
            int nCol = -1;

            nRow = User_Table.getSelectedRow();
            nCol = User_Table.getSelectedColumn();

            String id = null;
            String pw = null;
            String name = null;
            String email = null;
            String phone = null;
            String birth = null;
            String residence = null;

            if(nRow == -1 && nCol == -1) {
                JOptionPane.showMessageDialog(null, "선택된 값이 없습니다.");
            } else {
                Object Id = usermodel.getValueAt(nRow, 0);
                Object Pw = usermodel.getValueAt(nRow, 1);
                Object Name = usermodel.getValueAt(nRow, 2);
                Object Email = usermodel.getValueAt(nRow, 3);
                Object Phone = usermodel.getValueAt(nRow, 4);
                Object Birth = usermodel.getValueAt(nRow, 5);
                Object Residence = usermodel.getValueAt(nRow, 6);

                id = Id.toString();
                pw = Pw.toString();
                name = Name.toString();
                email = Email.toString();
                phone = Phone.toString();
                birth = Birth.toString();
                residence = Residence.toString();
                
                UserList Blackdata = new UserList();
                Blackdata.BWrite(id+"\t"+pw+"\t"+name+"\t"+email+"\t"+phone+"\t"+birth+"\t"+residence);
            }
            
            UserList Userdata = new UserList();
            Userdata.FRead();
            Userdata.Split();
            
            userinfo = Userdata.returUserinfo();
            
            for (int i = 0 ; i < userinfo.size() ; i++){
                if (userinfo.get(i).getId().equals(id)){
                    userinfo.remove(i);
                    BufferedWriter log = new BufferedWriter(new FileWriter("C:\\DB\\userList.txt", false));
                    log.close();
                    for (int j = 0; j < userinfo.size(); j++) {
                        String str = userinfo.get(j).getId() + "\t" + userinfo.get(j).getPw() + "\t" + userinfo.get(j).getName() + "\t" + userinfo.get(j).getEmail() + "\t" + userinfo.get(j).getPhone() + "\t" + userinfo.get(j).getBirth() + "\t" + userinfo.get(j).getResidence();
                        Userdata.FWrite(str);
                    }
                    JOptionPane.showMessageDialog(null, "블랙리스트에 추가되었습니다.");
                    Load_UserList_Button.doClick();
                    break;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(User_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BlackList_Add_ButtonActionPerformed

    private void BlackList_Del_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackList_Del_ButtonActionPerformed
        try {
            DefaultTableModel blackmodel = (DefaultTableModel) Black_Table.getModel();
            int nRow = -1;
            int nCol = -1;

            nRow = Black_Table.getSelectedRow();
            nCol = Black_Table.getSelectedColumn();

            String id = null;
            String pw = null;
            String name = null;
            String email = null;
            String phone = null;
            String birth = null;
            String residence = null;

            if(nRow == -1 && nCol == -1) {
                JOptionPane.showMessageDialog(null, "선택된 값이 없습니다.");
            } else {
                Object Id = blackmodel.getValueAt(nRow, 0);
                Object Pw = blackmodel.getValueAt(nRow, 1);
                Object Name = blackmodel.getValueAt(nRow, 2);
                Object Email = blackmodel.getValueAt(nRow, 3);
                Object Phone = blackmodel.getValueAt(nRow, 4);
                Object Birth = blackmodel.getValueAt(nRow, 5);
                Object Residence = blackmodel.getValueAt(nRow, 6);

                id = Id.toString();
                pw = Pw.toString();
                name = Name.toString();
                email = Email.toString();
                phone = Phone.toString();
                birth = Birth.toString();
                residence = Residence.toString();
                
                UserList Userdata = new UserList();
                Userdata.FWrite(id+"\t"+pw+"\t"+name+"\t"+email+"\t"+phone+"\t"+birth+"\t"+residence);
            }
            
            UserList Blackdata = new UserList();
            Blackdata.BRead();
            Blackdata.BSplit();
            
            blackinfo = Blackdata.returnBlackinfo();
            
            for (int i = 0 ; i < blackinfo.size() ; i++){
                if (blackinfo.get(i).getId().equals(id)){
                    blackinfo.remove(i);
                    BufferedWriter log = new BufferedWriter(new FileWriter("C:\\DB\\blackList.txt", false));
                    log.close();
                    for (int j = 0; j < blackinfo.size(); j++) {
                        String str = blackinfo.get(j).getId() + "\t" + blackinfo.get(j).getPw() + "\t" + blackinfo.get(j).getName() + "\t" + blackinfo.get(j).getEmail() + "\t" + blackinfo.get(j).getPhone() + "\t" + blackinfo.get(j).getBirth() + "\t" + blackinfo.get(j).getResidence();
                        Blackdata.BWrite(str);
                    }
                    JOptionPane.showMessageDialog(null, "블랙리스트가 해제되었습니다.");
                    Load_BlackKList_Button.doClick();
                    break;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(User_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BlackList_Del_ButtonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        AdminMenu am = new AdminMenu();
        am.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton BlackList_Add_Button;
    private javax.swing.JButton BlackList_Del_Button;
    private javax.swing.JTable Black_Table;
    private javax.swing.JButton Load_BlackKList_Button;
    private javax.swing.JButton Load_UserList_Button;
    private javax.swing.JTable User_Table;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
