/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.team.Delivery;
import deu.cse.team.mainmenu.MainMenu;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.DefaultListModel;
/**
 *
 * @author qjqmf
 */

public class Delivery_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Delivery_Frame
     */
    public Delivery_Frame() {
        initComponents();
        deliveryLog();
        setTitle("Delivery Page");
    }
    
    public void deliveryLog() {
        WareHouse warehouse = new WareHouse();
        Iterator<String> iterator = warehouse.createIterator();
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        delivery_List.setModel(listModel);
        
        Thread updater = new Thread(){
            @Override
            public void run(){
                while (iterator.hasNext()) {
                    String element = iterator.next();
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e){
                        System.out.println(e.getMessage());
                    }
                    listModel.addElement(element);
                }
            }
        };
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("C:\\DB\\DeliveryLog.txt"));
            String user = br.readLine();
            int to;
            if(user!=null) {
                to = Integer.parseInt(user);
                switch(to){
                    case 1:
                        listModel.addElement("출고 준비중");
                        warehouse.add("출고 완료");
                        warehouse.add("배송 준비중");
                        warehouse.add("배송 완료");
                        break;
                    case 2:
                        listModel.addElement("출고 준비중");
                        listModel.addElement("출고 완료");
                        warehouse.add("배송 준비중");
                        warehouse.add("배송 완료");
                        break;
                    case 3:
                        listModel.addElement("출고 준비중");
                        listModel.addElement("출고 완료");
                        listModel.addElement("배송 준비중");
                        warehouse.add("배송 완료");
                        break;
                    case 4:
                        listModel.addElement("출고 준비중");
                        listModel.addElement("출고 완료");
                        listModel.addElement("배송 준비중");
                        listModel.addElement("배송 완료");
                        break;
                    default:
                        break;
                }
            }
            else {
                warehouse.add("출고 준비중");
                warehouse.add("출고 완료");
                warehouse.add("배송 준비중");
                warehouse.add("배송 완료");
            }
            br.close();
        } catch (IOException e) {
            System.out.println("오류발생");
        }
        updater.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        delivery_List = new javax.swing.JList<>();
        Back_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel1.setText("배송 조회");

        jScrollPane1.setViewportView(delivery_List);

        Back_Button.setText("이전");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back_Button)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Back_Button)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        int log = delivery_List.getModel().getSize();
        String log_str = Integer.toString(log);
        try {
            File f1 = new File("C:\\DB\\DeliveryLog.txt");
            FileWriter writer = new FileWriter(f1);
            writer.write(log_str);
            writer.flush();
            writer.close();
        } catch (IOException e) {
            System.out.println("오류발생");
        }
        
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delivery_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JList<String> delivery_List;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
